[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
fs_permissions = [{ access = "read", path = "./broadcast" }]
ffi = false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options